import nodemailer from "nodemailer";
import fs from "fs";
import path from "path";

const user = process.env.GMAIL_USER;
const pass = process.env.GMAIL_PASS;

const suite = process.env.TEST_SUITE || "all";
const testStatus = process.env.TEST_STATUS || "Failed";
const reportPath = path.resolve("playwright-report/index.html");
const reportUrl = process.env.REPORT_URL || null;
const pipelineName = process.env.PIPELINE_NAME || "QA Automation Pipeline";
const duration = process.env.TEST_DURATION || "-";

const resultsJsonPath = "results.json";
let passed = 0, failed = 0, total = 0;

try {
  const raw = fs.readFileSync(resultsJsonPath, "utf8");
  const json = JSON.parse(raw);

  const scan = (n) => {
    if (!n) return;
    if (n.status === "passed") passed++;
    if (n.status === "failed") failed++;
    if (n.status) total++;
    if (n.suites) n.suites.forEach(scan);
    if (n.specs) n.specs.forEach(scan);
  };

  scan(json);
} catch (err) {
  console.error("JSON read error:", err.message);
}

let reportExists = fs.existsSync(reportPath);

// Create Email Body
let emailBody = `
<div style="font-family:Arial;background:#eef3fc;padding:14px;">
<div style="background:#fff;padding:14px;border-radius:6px;max-width:520px;border:1px solid #c5d3f2">
  <h2 style="color:#000;margin:0 0 10px 0;">Playwright CI Test Report</h2>

  ${reportUrl ? `
    <p><a href="${reportUrl}" target="_blank"
       style="padding:10px 14px;background:#1976d2;color:#fff;font-size:13px;border-radius:6px;text-decoration:none;font-weight:bold;">
       View Full HTML Report
    </a></p>` : ""}

  <p>Automated report generated by <b>${pipelineName}</b></p>

  <table style="width:100%;font-size:13px;">
    <tr><td><b>Suite:</b></td><td>${suite}</td></tr>
    <tr><td><b>Status:</b></td><td style="color:${testStatus==="Passed"?"green":"red"}">${testStatus}</td></tr>
    <tr><td><b>Duration:</b></td><td>${duration}</td></tr>
    <tr><td><b>Passed:</b></td><td>${passed}</td></tr>
    <tr><td><b>Failed:</b></td><td>${failed}</td></tr>
    <tr><td><b>Total:</b></td><td>${total}</td></tr>
    <tr><td><b>Timestamp:</b></td><td>${new Date().toLocaleString()}</td></tr>
  </table>
</div>
</div>
`;

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: { user, pass },
});

const mailOptions = {
  from: `"Playwright CI" <${user}>`,
  to: ["gopalakrishnan93843@gmail.com", "gokulcoal78752@gmail.com"],
  cc: ["gokulgokul78752@gmail.com"],
  bcc: ["gokulakrishnan1607@gmail.com"],
  subject: `Playwright Report • ${suite} • ${testStatus}`,
  html: emailBody,
  attachments: reportExists
    ? [{ filename: "playwright-report.html", path: reportPath }]
    : [],
};

try {
  await transporter.sendMail(mailOptions);
  console.log("📨 Email successfully sent!");
} catch (err) {
  console.error("❌ Email failed:", err.message);
}
