import nodemailer from "nodemailer";
import fs from "fs";
import path from "path";

// Gmail credentials
const user = process.env.GMAIL_USER;
const pass = process.env.GMAIL_PASS;

// Suite + status
const suite = process.env.TEST_SUITE || "all";
const testStatus = process.env.TEST_STATUS || "Failed";

// S3 + HTML Report
const reportPath = path.resolve("playwright-report/index.html");
const reportUrl = process.env.REPORT_URL || null;

// Metadata
const pipelineName = process.env.PIPELINE_NAME || "QA Automation Pipeline";
const duration = process.env.TEST_DURATION || "-";

// ---------------------------------------------------------------
// 📊 STEP 1 — Extract Test Stats from Playwright JSON
// ---------------------------------------------------------------
const resultsJsonPath = path.resolve("playwright-report/results.json");

let passed = 0;
let failed = 0;
let total = 0;

try {
  const raw = fs.readFileSync(resultsJsonPath, "utf8");
  const results = JSON.parse(raw);

  // Traverse JSON recursively
  function scan(node) {
    if (!node || typeof node !== "object") return;

    if ("ok" in node && node.title) {
      total++;
      node.ok ? passed++ : failed++;
      return;
    }

    if (Array.isArray(node)) node.forEach(scan);
    else Object.values(node).forEach(scan);
  }

  scan(results);

  console.log("📊 Test Summary:", { passed, failed, total });

} catch (err) {
  console.log("⚠️ No JSON results found:", err.message);
}

// ---------------------------------------------------------------
// 📁 Check HTML report exists
// ---------------------------------------------------------------
let reportExists = false;
try {
  fs.accessSync(reportPath);
  reportExists = true;
} catch {}

// ---------------------------------------------------------------
// ✉️ Configure Email Transport
// ---------------------------------------------------------------
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: { user, pass },
});

// ---------------------------------------------------------------
// 🎨 Build Email Body (same design you use)
// ---------------------------------------------------------------
let emailBody = `
  <div style="font-family: Arial; color:#222; background:#eef3fc; padding:14px;">
    <div style="background:#fff; border-radius:6px; padding:14px; border:1px solid #c5d3f2; max-width:520px;">

      <h2 style="color:#000; margin:0 0 10px 0; font-size:20px; font-weight:700;">
        Playwright CI Test Report
      </h2>

      ${reportUrl ? `
        <p style="margin:10px 0 18px 0;">
          <a href="${reportUrl}" target="_blank"
             style="display:inline-block;background:#1976d2;color:#fff;
                    padding:10px 14px;font-weight:bold;border-radius:6px;
                    text-decoration:none;font-size:13px;">
            View Full HTML Report
          </a>
        </p>
      ` : ""}

      <p style="margin:0 0 12px 0; font-size:12px; color:#555;">
        Automated report generated by <b>${pipelineName}</b>
      </p>

      <table style="width:100%; font-size:12px; border-collapse:collapse;">
        <tr><td><b>Suite:</b></td><td>${suite}</td></tr>
        <tr>
          <td><b>Status:</b></td>
          <td style="color:${testStatus === "Passed" ? "green" : "red"};">
            ${testStatus}
          </td>
        </tr>
        <tr><td><b>Duration:</b></td><td>${duration}</td></tr>
        <tr><td><b>Timestamp:</b></td><td>${new Date().toLocaleString()}</td></tr>
      </table>

      <div style="margin-top:14px; background:#f4f6ff; padding:10px; border-left:4px solid #1976d2;">
        <b>📊 Test Summary</b><br>
        ✔ Passed: ${passed}<br>
        ❌ Failed: ${failed}<br>
        📦 Total: ${total}
      </div>

      ${reportExists ? `
        <div style="margin-top:12px; background:#eaf2ff; padding:10px;
                    border-left:4px solid #1976d2;">
          The Playwright HTML report is attached below for offline viewing.
        </div>
      ` : ""}
      
      <hr style="border:none;border-top:1px solid #ddd;margin:16px 0;">
      <p style="font-size:11px;color:#777;">
        Sent automatically by <b>Playwright CI</b> — do not reply to this email.
      </p>

    </div>
  </div>
`;

// ---------------------------------------------------------------
// Attach Report File
// ---------------------------------------------------------------
const mailOptions = {
  from: `"Playwright CI" <${user}>`,
  to: ["gopalakrishnan93843@gmail.com", "gokulcoal78752@gmail.com"],
  cc: ["gokulgokul78752@gmail.com"],
  bcc: ["gokulakrishnan1607@gmail.com"],
  subject: `Playwright Report • ${suite} • ${testStatus}`,
  html: emailBody,
};

if (reportExists) {
  mailOptions.attachments = [
    { filename: "playwright-report.html", path: reportPath }
  ];
}

// ---------------------------------------------------------------
// 🚀 Send Email (never break pipeline)
// ---------------------------------------------------------------
try {
  await transporter.sendMail(mailOptions);
  console.log("📨 Email sent successfully!");
} catch (err) {
  console.error("❌ Email send failed:", err.message);
  process.exit(0);
}
